server {
    listen 80;
    listen [::]80;

    server_name 127.0.0.1;

    root /var/www/devops-hackathon-de003-daotruongson/src
    index index.html

    access_log /var/log/nginx/dev.access.log;
    error_log /var/log/nginx/dev.error.log;


    location / {
        allow all
        try_files $uri $uri/ =404;
    }
}